const STAGES = { seed: '', seedling: '', grown: '', fruiting: '', dead: '' };

export const SEEDS = [
  {
    id: 'velour_bloom',
    name: 'Velour Bloom',
    description: 'A deep-petalled flower with velvety purple hues, warm to the touch even in winter.',
    color: '#7B3F8C',
    locationId: 'the_glasshouse',
    symbol: '✿',
    stages: { ...STAGES },
  },
  {
    id: 'cinder_fern',
    name: 'Cinder Fern',
    description: 'A hardy fern with ashen fronds that curl at the edges like cooling embers.',
    color: '#9E9E9E',
    locationId: 'the_fernery',
    symbol: '⌁',
    stages: { ...STAGES },
  },
  {
    id: 'mirewort',
    name: 'Mirewort',
    description: 'A moisture-loving plant that roots in dark water and breathes clean air upward.',
    color: '#2E6B3E',
    locationId: 'the_bogwood',
    symbol: '≋',
    stages: { ...STAGES },
  },
  {
    id: 'stonecress',
    name: 'Stonecress',
    description: 'Pale clusters that bloom in cracks and crevices, indifferent to cold stone.',
    color: '#BDBDBD',
    locationId: 'the_terrace',
    symbol: '◻',
    stages: { ...STAGES },
  },
  {
    id: 'ember_weed',
    name: 'Ember Weed',
    description: 'A sharp crimson weed that thrives in cold, dry air, its tips perpetually warm.',
    color: '#B71C1C',
    locationId: 'the_coldhouse',
    symbol: '✦',
    stages: { ...STAGES },
  },
  {
    id: 'wanderbloom',
    name: 'Wanderbloom',
    description: 'An unruly orange flower that spreads its seeds on the slightest breeze.',
    color: '#E67E22',
    locationId: 'the_nursery',
    symbol: '❁',
    stages: { ...STAGES },
  },
  {
    id: 'goldthread',
    name: 'Goldthread',
    description: 'Thin yellow filaments that weave between other plants, connecting root systems.',
    color: '#F9A825',
    locationId: 'the_orchard',
    symbol: '✵',
    stages: { ...STAGES },
  },
  {
    id: 'salthorn',
    name: 'Salthorn',
    description: 'A pale, spiny succulent adapted to mineral-rich, arid ground.',
    color: '#F5F0DC',
    locationId: 'the_salt_flats',
    symbol: '⋄',
    stages: { ...STAGES },
  },
  {
    id: 'rainfall_lily',
    name: 'Rainfall Lily',
    description: 'A tall blue lily that blooms only after heavy rain, holding water in its cup.',
    color: '#1565C0',
    locationId: 'the_cutting_garden',
    symbol: '✧',
    stages: { ...STAGES },
  },
  {
    id: 'quietbranch',
    name: 'Quietbranch',
    description: 'A slow-growing shrub whose stems never creak, even in high wind.',
    color: '#78909C',
    locationId: 'the_walled_garden',
    symbol: '❧',
    stages: { ...STAGES },
  },
  {
    id: 'thornwhisper',
    name: 'Thornwhisper',
    description: 'Dense, pale-thorned canes that make a faint sound when air moves through them.',
    color: '#B0BEC5',
    locationId: 'the_thicket',
    symbol: '⋈',
    stages: { ...STAGES },
  },
  {
    id: 'glassroot',
    name: 'Glassroot',
    description: 'A translucent, wavering root-plant that grows toward underground light.',
    color: '#4FC3F7',
    locationId: 'the_undercroft',
    symbol: '◈',
    stages: { ...STAGES },
  },
  {
    id: 'ironmoss',
    name: 'Ironmoss',
    description: 'A dense, dark moss that clings to high branches and filters morning mist.',
    color: '#546E7A',
    locationId: 'the_canopy',
    symbol: '♧',
    stages: { ...STAGES },
  },
  {
    id: 'duskbell',
    name: 'Duskbell',
    description: 'Deep violet bell-flowers that open only at twilight, releasing a cool scent.',
    color: '#4527A0',
    locationId: 'the_still_pool',
    symbol: '◆',
    stages: { ...STAGES },
  },
  {
    id: 'murmuring_sage',
    name: 'Murmuring Sage',
    description: 'A soft-leaved sage whose rustling sounds like distant conversation.',
    color: '#90A4AE',
    locationId: 'the_seedbank',
    symbol: '❦',
    stages: { ...STAGES },
  },
];

export const SEED_MAP = Object.fromEntries(SEEDS.map(s => [s.id, s]));
